<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ID' => 'ID',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => '修改失败，请重试!',
    'BACKEND_INDEX_SUBTITLE' => '银行交易列表',
    'BACKEND_INDEX_TITLE' => '银行交易',
    'BACKEND_UPDATE_SUBMIT' => '修改',
    'BACKEND_UPDATE_SUBTITLE' => '修改数据',
    'BACKEND_UPDATE_TITLE' => '银行交易',
    'PURCHASE' => '商品采购',
    'PRODUCT' => '产品销售',
    'BANK' => '银行交易',
    'CASH' => '现金交易',
    'bank' => '银行交易',
    'cash' => '现金交易',
    'COST' => '成本结转',
];