<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ID' => 'ID',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => '修改失败，请重试!',
    'BACKEND_INDEX_SUBTITLE' => '银行交易列表',
    'BACKEND_INDEX_TITLE' => '银行交易',
    'BACKEND_UPDATE_SUBMIT' => '修改',
    'BACKEND_UPDATE_SUBTITLE' => '修改数据',
    'BACKEND_UPDATE_TITLE' => '银行交易',
    'PURCHASE' => '商品采购',
    'PRODUCT' => '产品销售',
    'BANK' => '银行交易',
    'CASH' => '现金交易',
    'bank' => '银行交易',
    'cash' => '现金交易',
    'COST' => '成本结转',
    'SALARY' => '员工工资',
    'REIMBURSE' => '员工报销',
    'PREPRODUCT' => '预收',
    'PREPURCHASE' => '预付',

    '首页' => 'Home',
    '总账' => 'General Ledger',
    '科目表' => 'Chart of Accounts',
    '期初余额' => 'Opening Balance',
    '整理凭证' => 'Clean Deleted Invoice',
    '打印凭证' => 'Print Invoice',
    '过账' => 'Posting Entry',
    '期末结转' => 'Closing Entry',
    '结账' => 'Closing Accounts',
    '反结账' => 'Anti-closing',
    '报表' => 'Financial Statement',
    '客户' => 'Client',
    '供应商' => 'Supplier',
    '库存商品' => 'Inventory',
    '成本结转' => 'COGS',
    '期初库存' => 'Opening Balance',
    '长期资产' => 'Long-term Asset',
    '新建项目' => 'New Projects',
    '固定资产' => 'Fixed Assets',
    '在建工程' => 'Construction in Progress',
    '无形资产' => 'Intangible Assets',
    '长期待摊' => 'Deferred Expense',
    '员工' => 'Employee',
    '员工列表' => 'List of Employees',
    '员工工资' => 'Employee Salary',
    '员工报销' => 'Employee Reimbursement',
    '部门管理' => 'Department',
    '部门' => 'Department',

    '基本设置' => 'Basic Setting',
    '账套信息' => 'Book Information',
    '账套权限' => 'Authorization',
    '参数设置' => 'Configuration',
    '项目列表' => 'List of Projects',
    '退出' => 'Sign Out',
    '系统选项' => 'User Setting',
    '帮助' => 'Help',
    '常见问题' => 'FAQ',
    '如何录入凭证' => 'How to record invoices',
    '更多内容' => 'More...',
    '专业培训' => 'Professional Training',
    '服务热线' => 'Service Hotline',

    '搜索凭证' => 'Search Invoices',
    '逐月查询' => 'Search by Months',
    '审核凭证' => 'Approve Voucher',
    '输入凭证字号，日期，内容等' => 'Search Invoices no., Date, Memo...',

    '新建' => 'Create New',
    '凭证' => 'Invoices',
    '其他' => 'Others',
    '会计科目' => 'Accounting',

    '采购交易' => 'Purchase Transaction',
    '产品销售' => 'Sales Transaction',
    '银行交易' => 'Bank Transaction',
    '现金流水' => 'Cash Transaction',
    '现金交易' => 'Cash Transaction',
    '往来调整' => 'Adjustments',

    '已导入数据查看' => 'Import History',
    '组织' => 'Organize',
    '流动资产' => 'Current assets',
    '运营支出' => 'Operating expenses',

    '库存现金' => 'Cash in stock',
    '银行存款' => 'Cash in bank',
    '应收账款' => 'Account receivable',

    //记账时，选择的支出为类别，首页饼图按类别显示金额需要用到这个数据
    '工资社保' => 'Social Security Benefits',
    '支付押金' => 'Deposit',
    '借出款项' => 'Loans To Others',
    '归还借款' => 'Repayment Of Loans',
    '投资支出' => 'Investment',
    '材料销售' => 'Material Sales',
    '技术转让' => 'Transfer Of Technology',
    '资产租赁' => 'Capital Lease',
    '支付股利' => 'Pay Dividends',
    '支付税金' => 'Pay Raxes',
    '现金提取' => 'Cash Withdrawal',
    '银行转账' => 'Bank Transfer',
    '汇兑损益' => 'Exchange Gains And Losses',
    '其他支出' => 'Others',
    '供应商采购' => 'Purchasing',
    '利息手续费'=> 'Interest Charges',

];