<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_ID' => 'ID',
    'BACKEND_FLASH_FAIL_ADMIN_UPDATE' => '修改失败，请重试!',
    'BACKEND_INDEX_SUBTITLE' => '银行交易列表',
    'BACKEND_INDEX_TITLE' => '银行交易',
    'BACKEND_UPDATE_SUBMIT' => '修改',
    'BACKEND_UPDATE_SUBTITLE' => '修改数据',
    'BACKEND_UPDATE_TITLE' => '银行交易',
    'PURCHASE' => '商品采购',
    'PRODUCT' => '产品销售',
    'BANK' => '银行交易',
    'CASH' => '现金交易',
    'bank' => '银行交易',
    'cash' => '现金交易',
    'COST' => '成本结转',
    'SALARY' => '员工工资',
    'REIMBURSE' => '员工报销',
    'PREPRODUCT' => '预收',
    'PREPURCHASE' => '预付',


    '交易信息修改' => 'Update',
    '科目表管理' => 'Subjects Manage',
    '添加科目' => 'New Subject',
    '导出' => 'Export',
    '导入' => 'Import',
    '已导入数据' => 'History',
    '导入银行交易' => 'Bank Transaction',
    '导入现金交易' => 'Cash Transaction',
    '手动录入凭证' => 'Adjustments',
    '全屏' => 'Full Screen',
    '银行原始数据管理' => 'Bank Transaction History',
    '现金原始数据管理' => 'Cash Transaction History',
    '采购原始数据管理' => 'Purchase Transaction History',
    '销售原始数据管理' => 'Sales Transaction History',
    '员工工资原始数据管理' => 'Employee Salary History',
    '员工报销原始数据管理' => 'Employee Reimbursement History',
//    '采购原始数据管理' => 'Cash Transaction History',
//    '采购原始数据管理' => 'Cash Transaction History',
//    '采购原始数据管理' => 'Cash Transaction History',
    '总金额' => 'Total',
    '保存凭证' => 'Save',
    '记账' => 'Setting',
    '拆分' => 'Split',
    '删分' => 'Delete',
    '首页' => 'First Page',
    '下一页' => 'Next',
    '上一页' => 'Previous',
];