<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    '单位：百万元' => '单位：百万元',
    '经营收支报表' => 'Statement of Profit and Loss',
    '全部报表' => 'Financial Statement',
    '财务类' => 'Financial',
    '行政类' => 'Administrative',

    '财务报表' => 'Financial',
    '资产负债表' => 'Balance sheet',
    '损益表' => 'Income statement',
    '科目余额表' => 'Trial Balance',
    '明细表' => 'Subsidiary Ledger',
    '现金流量表' => 'Cashflow Statement',

    '行政报表' => 'Administrative',
    '供应商表' => 'Statement of Suppliers',
    '客户表' => 'Statement of Clients',
    '部门表' => 'Statement of Departments',

    '请选择报表日期' => 'Date',
    '查看报表' => 'View Report',
    '日期' => 'Date',
    '编制单位' => 'Preparation Unit',
    '金额单位' => 'Monetary unit',

    //资产负债表
    '资 产 负 债 表' => 'BALANCE SHEET',
    '资产' => 'Assets',
    //'年初数' => 'Assets',
    //'期末数' => 'Assets',
    '金额单位：元' => 'Unit: RMB',
    '流动资产' => 'Current Assets',
    //'流动负债' => 'Assets',
    '货币资金' => 'Cash and cash equivalents',
    '短期借款' => 'Short-term borrowing',

];